import { ComAtprotoRepoApplyWrites, ComAtprotoRepoCreateRecord } from '@atcute/atproto';
import { AppBskyFeedGenerator } from '@atcute/bluesky';
import { BSKY_IDENTIFIER, BSKY_PASSWORD, DID, FEEDS_DOMAIN } from '../config.js';
import logger from '../backend/logger.js';
import { labelDefinitions } from '../utils/label-definitions.js';
import { getFeedRkeyFromLabelIdentifier } from '../utils/feed-helpers.js';
import { loginAgent } from './util/index.js';
import { Cid, Did, ResourceUri } from '@atcute/lexicons';
import * as v from '@atcute/lexicons/validations';
import { AtUri } from '@atproto/syntax';
import { Records } from '@atcute/lexicons/ambient';
import RichText from '@atcute/bluesky-richtext-builder';

async function publishFeeds() {
    const { agent, session } = await loginAgent({
        identifier: BSKY_IDENTIFIER,
        password: BSKY_PASSWORD,
    });

    const feeds: {
        cid: Cid;
        uri: AtUri;
        value: AppBskyFeedGenerator.Main;
        rkey: string;
    }[] = [];

    {
        const result: {
            records: {
                cid: Cid;
                readonly uri: AtUri;
                value: v.InferInput<Records['app.bsky.feed.generator']>;
            }[];
            cursor?: string | undefined;
        } = await agent.paginatedList({
            repo: session.did,
            collection: 'app.bsky.feed.generator',
            limit: 100,
            reverse: true,
        });

        feeds.push(
            ...result.records.map((e) => ({
                ...(e as {
                    cid: Cid;
                    uri: AtUri;
                    value: AppBskyFeedGenerator.Main;
                }),
                rkey: e.uri.rkey,
            })),
        );
    }

    const feedsByRkey = Object.fromEntries(feeds.map((feed) => [feed.rkey, feed.value]));

    logger.info(feeds.length, 'feeds.length');

    const creates: Array<(ComAtprotoRepoApplyWrites.Create | ComAtprotoRepoApplyWrites.Update) & { $type: {} }> = [];
    const updates: Array<ComAtprotoRepoApplyWrites.Update & { $type: {} }> = [];
    const deletes: Array<ComAtprotoRepoApplyWrites.Delete & { $type: {} }> = [];

    for (const labelIdentifier of Object.keys(labelDefinitions)) {
        logger.info(labelIdentifier);

        const description = new RichText()
            .addText(`${truncate(labelDefinitions[labelIdentifier].locales[0].description)}\n\nAuto-generated by `)
            .addMention(`@${BSKY_IDENTIFIER}`, DID as Did)
            .build();

        (labelIdentifier in feedsByRkey ? updates : creates).push({
            $type:
                labelIdentifier in feedsByRkey
                    ? 'com.atproto.repo.applyWrites#update'
                    : 'com.atproto.repo.applyWrites#create',

            collection: 'app.bsky.feed.generator',
            rkey: labelIdentifier,
            value: {
                $type: 'app.bsky.feed.generator',

                did: `did:web:${FEEDS_DOMAIN}`,
                displayName: truncate(`Tag: ${labelDefinitions[labelIdentifier].locales[0].name}`, 24),
                description: description.text,
                descriptionFacets: description.facets,

                labels: {
                    $type: 'com.atproto.label.defs#selfLabels',
                    values: [
                        {
                            val: labelIdentifier,
                        },
                    ],
                },

                createdAt: feedsByRkey[labelIdentifier]?.createdAt ?? new Date().toISOString(),
            } satisfies AppBskyFeedGenerator.Main,
        });
    }

    const feedsToRemove = feeds.filter(
        (e) => !creates.find((e1) => e1.rkey == e.rkey) && !updates.find((e1) => e1.rkey == e.rkey),
    );
    for (const feed of feedsToRemove) {
        deletes.push({
            $type: 'com.atproto.repo.applyWrites#delete',

            collection: 'app.bsky.feed.generator',
            rkey: feed.rkey,
        });
    }

    logger.info(`Creating ${creates.length} entries`);
    for (const chunk of chunks(creates, 10)) {
        logger.info(chunk, `Writing chunk of size ${chunk.length}`);
        await agent.batchWrite({
            repo: session.did,
            writes: chunk,
            validate: true,
        });
    }

    logger.info(`Updating ${updates.length} entries`);
    for (const chunk of chunks(updates, 10)) {
        logger.info(chunk, `Writing chunk of size ${chunk.length}`);
        await agent.batchWrite({
            repo: session.did,
            writes: chunk,
            validate: true,
        });
    }

    logger.info(`Deleting ${deletes.length} entries`);
    for (const chunk of chunks(deletes, 10)) {
        logger.info(chunk, `Writing chunk of size ${chunk.length}`);
        await agent.batchWrite({
            repo: session.did,
            writes: chunk,
            validate: true,
        });
    }
}

function* chunks<T>(arr: T[], chunkSize = 10): Generator<T[]> {
    for (let i = 0; i < arr.length; i += chunkSize) {
        yield arr.slice(i, i + chunkSize);
    }
}

await publishFeeds();

function truncate(description: string, len = 250) {
    if (description.length < len) return description;
    return description.slice(0, len - 3) + '...';
}
