import { AppBskyFeedGenerator, At, Brand, ComAtprotoRepoApplyWrites, ComAtprotoRepoCreateRecord } from "@atcute/client/lexicons";
import { loginAgent } from "#skyware/labeler/scripts/util.js";
import { BSKY_IDENTIFIER, BSKY_PASSWORD, DID, FEEDS_DOMAIN } from "../config.js";
import logger from "../logger.js";
import { labelDefinitions } from "../utils/label-definitions.js";
import { credentialManager } from "../session.js";
import { RichText } from "#skyware/bot";
import { XRPCError } from "@atcute/client";

async function publishFeeds() {
	const { agent, session } = await loginAgent({
        identifier: BSKY_IDENTIFIER,
        password: BSKY_PASSWORD,
        credentialManager
    });

    const feeds: {
        cid: At.CID;
        uri: At.Uri;
        value: AppBskyFeedGenerator.Record;
        rkey: string;
    }[] = [];

    {
        let cursor: string | undefined = undefined;
        do {
            logger.info(`Listing feeds ${cursor}`);
            const result = await agent.get('com.atproto.repo.listRecords', {
                params: {
                    repo: session.did,
                    collection: 'app.bsky.feed.generator',
                    limit: 100,
                }
            });

            if (!result.data.records.length) {
                break;
            }

            feeds.push(...result.data.records.map(e => ({
                ...e as {
                    cid: At.CID;
                    uri: At.Uri;
                    value: AppBskyFeedGenerator.Record;
                },
                rkey: e.uri.slice(e.uri.lastIndexOf('/') + 1),
            })));

            if (result.data.cursor == cursor) break;

            cursor = result.data.cursor;

            if (!cursor) break;
        } while (cursor);
    }

    const feedsByIdentifier = Object.fromEntries(feeds.map(feed => [feed.rkey, feed.value]))

    const creates: Array<Brand.Union<ComAtprotoRepoApplyWrites.Create | ComAtprotoRepoApplyWrites.Update>> = [];
    const updates: Array<Brand.Union<ComAtprotoRepoApplyWrites.Update>> = [];
    const deletes: Array<Brand.Union<ComAtprotoRepoApplyWrites.Delete>> = [];

    for (const labelIdentifier of Object.keys(labelDefinitions)) {
        logger.info(labelIdentifier);

        const description = new RichText()
            .addText(`${truncate(labelDefinitions[labelIdentifier].locales[0].description)}\n\nAuto-generated by `)
            .addMention(`@${BSKY_IDENTIFIER}`, DID as At.DID)
            .build();

        (labelIdentifier in feedsByIdentifier ? updates : creates).push({
            $type: labelIdentifier in feedsByIdentifier ? 'com.atproto.repo.applyWrites#update' : 'com.atproto.repo.applyWrites#create',

            collection: "app.bsky.feed.generator",
            rkey: labelIdentifier,
            value: {
                $type: "app.bsky.feed.generator",

                did: `did:web:${FEEDS_DOMAIN}`,
                displayName: truncate(`Tag: ${labelDefinitions[labelIdentifier].locales[0].name}`, 24),
                description: description.text,
                descriptionFacets: description.facets,

                labels: {
                    $type: 'com.atproto.label.defs#selfLabels',
                    values: [{
                        val: labelIdentifier,
                    }]
                },

                createdAt: feedsByIdentifier[labelIdentifier]?.createdAt ?? new Date().toISOString(),
            } satisfies AppBskyFeedGenerator.Record,
        });
    }

    const feedsToRemove = feeds.filter(e => !creates.find(e1 => e1.rkey == e.rkey) && !updates.find(e1 => e1.rkey == e.rkey));
    for (const feed of feedsToRemove) {
        deletes.push({
            $type: 'com.atproto.repo.applyWrites#delete',

            collection: "app.bsky.feed.generator",
            rkey: feed.rkey,
        });
    }

    logger.info(creates, 'Creating');
    for (const chunk of chunks(creates, 1)) {
        logger.info(chunk, 'Writing chunk');
        await agent.call('com.atproto.repo.applyWrites', {
            data: {
                repo: session.did,
                writes: chunk as Brand.Union<ComAtprotoRepoApplyWrites.Create | ComAtprotoRepoApplyWrites.Update | ComAtprotoRepoApplyWrites.Delete>[],
                validate: true,
            }
        })
    }

    logger.info(creates, 'Updating');
    for (const chunk of chunks(updates, 10)) {
        logger.info(chunk, 'Writing chunk');
        await agent.call('com.atproto.repo.applyWrites', {
            data: {
                repo: session.did,
                writes: chunk as Brand.Union<ComAtprotoRepoApplyWrites.Create | ComAtprotoRepoApplyWrites.Update | ComAtprotoRepoApplyWrites.Delete>[],
                validate: true,
            }
        })
    }

    logger.info(creates, 'Deleting');
    for (const chunk of chunks(deletes, 10)) {
        logger.info(chunk, 'Writing chunk');
        await agent.call('com.atproto.repo.applyWrites', {
            data: {
                repo: session.did,
                writes: chunk as Brand.Union<ComAtprotoRepoApplyWrites.Create | ComAtprotoRepoApplyWrites.Update | ComAtprotoRepoApplyWrites.Delete>[],
                validate: true,
            }
        })
    }
}

function *chunks<T>(arr: T[], chunkSize = 10): Generator<T[]> {
    for (let i = 0; i < arr.length; i += chunkSize) {
        yield arr.slice(i, i + chunkSize);
    }
}

await publishFeeds();

function truncate(description: string, len = 250) {
    if (description.length < len) return description;
    return description.slice(0, len - 3) + '...';
}
